### PR TITLE
Handle delete cases (fixes #135)

### LINKED ISSUE #135: Medium breaks in Firefox when deleting too much
In Firefox, if I create a new Medium editor with default settings, then hit backspace twice, the editor no longer works properly. Pressing return to add a paragraph will add the paragraph for a second and then immediately delete it. This also happens when trying to make text bold or italic: it happens for a second and then goes away.

Clicking away from the editor and clicking back reinitializes and fixes it. But it's a major annoyance if any user accidentally does this, or decides to do Select All and then backspace.

I tried doing a console.log about what the html of the Medium div was on every keyup. When I click on it before pressing any keys, it contains `<p>&nbsp;</p>` (by the way, I'd rather it didn't start with that nbsp if possible). One backspace produces `<p><br></p>`, and then a second backspace produces `an empty string`and the div visually shrinks.

This problem doesn't occur in Chrome, just Firefox.

### PR DESCRIPTION
**Pull request by vegetableman**
fixes #135 

This handles double delete cases mentioned in the issue and works across all browsers. Also, it sets the cursor position for initial paragraph's so as to maintain the text entry within the ```p``` tags.

### CODE REVIEW

**Comment by robertleeplummerjr** [comment]
Also, here is how I call an event: https://github.com/jakiestfu/Medium.js/blob/master/test/paste.js#L80

**Comment by vegetableman** [comment]
@robertleeplummerjr my bad. Forgot about pushing this build fix, the issue being, it added double quotes ```"``` on beginning and end of the concatenated script making it a string. I am totally cool with bash files (gulp/grunt are sort of redundant).

**Comment by vegetableman** [comment]
@robertleeplummerjr Have added tests. Since I have made few changes to the build file, let me know if you face any issues with it.

**Comment by robertleeplummerjr** [comment]
*high fives @vegetableman

**Comment by vegetableman** [comment]
:+1:

**Pull request merged**
