### PR TITLE
AMD support

### PR DESCRIPTION
**Pull request by DimitarChristoff**
Addresses #104 but it's not a great solution as such - requires use of the relatively unknown `bundles` config in RequireJS which has been around since 2.1.11 only (at 2.1.15 now). 

Creates 2 modules with ids `medium-wild` and `medium-domesticated` - requiring the domesticated without the shim for Undo and Rangy will fail, which is what you'd expect if you have not wired it all up.

Looking to the future, Undo does not seem updated much, chances of it getting proper AMD support are slim. Rangy can do with a tiny PR to make modules consistent by returning the object they decorate, which will make the following hack obsolete:

```javascript
define('medium-domesticated', ['undo', 'rangy/rangy-classapplier'], function(Undo) {
	var rangy = require('rangy/rangy-core'); // resolved!
	return factory(rangy, Undo);
});
```
and replaced by simply `define('medium-domesticated', ['undo', 'rangy/rangy-classapplier'], factory)`

### CODE REVIEW

**Comment by robertleeplummerjr** [comment]
wild mode is gone in master.  Can we work together to ensure we get a proper amd module now?

**Comment by JSteunou** [comment]
I'm sorry I'm really out of free time those days :(

**Comment by DimitarChristoff** [comment]
I will send a pr this weekend no worries

On Saturday, January 31, 2015, Jérôme Steunou <notifications@github.com>
wrote:

> I'm sorry I'm really out of free time those days :(
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jakiestfu/Medium.js/pull/105#issuecomment-72313453>.
>


-- 
Dimitar Christoff

"JavaScript is to JAVA what hamster is to ham"
@D_mitar - https://github.com/DimitarChristoff

**Comment by robertleeplummerjr** [comment]
bump

**Comment by dbackeus** [comment]
+1

**Comment by DimitarChristoff** [comment]
I've moved away from requirejs/amd/umd and gone to browserify/webpack approach. 

having said that, #163 is right but not i don't like the plumbing fix to `window.Rangy` etc. 

also, passing references  into a closure as a one-off is not a good practice for a dom-centric library, eg, working in popup windows will fail as the references will be opener `window` / `document` objects, where the library first gets loaded. 

given how long it's taken, pending conflicts etc, safe to assume this won't get merged/go forward. i am gonna close it.

**Comment by robertleeplummerjr** [comment]
Thanks for the hard work in any case.

**Comment by dbackeus** [comment]
Actually webpack support is what I was looking for but in my ignorance I thought this was all related, thanks :)

**Comment by robertleeplummerjr** [comment]
nice!

On Fri, Dec 11, 2015 at 12:44 PM, David Backeus <notifications@github.com>
wrote:

> Actually webpack support is what I was looking for but in my ignorance I
> thought this was all related, thanks :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jakiestfu/Medium.js/pull/105#issuecomment-164000860>.
>



-- 
Robert Plummer

**Pull request closed without merging**
